### ISSUE TITLE
Doesn't sync date nor timecode

### ISSUE THREAD

**Issue by abourget** [deric/DaVinciResolve-metadata#5]
Is there no way to adjust the creation date and timecode?
My only concern is that Davinci Resolve starts picking up the creation time properly from the EXIF data instead of the filesystem or whatever else. I'm coming from Lightworks, where it never failed to pick up the actual date from the media.
This script is setting a bunch of attribute, but I'm wondering if it can handle tweaking Timecode + Date?

thanks!

**Comment by deric** [comment]
Yes, there is.

| Davinci Resolve starts picking up the creation time properly from the EXIF data instead of the filesystem

Filesystem date could be easily wrong, assuming you copied the file from another disk or backup. EXIF usually contains `CreateDate` or  `DateTimeOriginal` (or both) which tends to be the best source of information when was the video taken. Depending on your editing software there might be other metadata fields or the time information might be completely missing.

Try fetching the EXIF dates from your media file: 
```
$ exiftool -time:all -G1 -a -s your_video.mov
[System]        FileModifyDate                  : 2020:10:24 12:42:53+02:00
[System]        FileAccessDate                  : 2021:08:08 14:35:12+02:00
[System]        FileInodeChangeDate             : 2020:10:24 12:42:53+02:00
[IFD0]          ModifyDate                      : 2018:12:02 23:04:20
[ExifIFD]       DateTimeOriginal                : 2018:09:14 18:27:18
[ExifIFD]       CreateDate                      : 2018:09:14 18:27:18
```
You can choose in the select box which EXIF field should be used as the DaVinci Resolve date time.

**Comment by abourget** [comment]
hmm.. but I don't see a "Date" field on the left side of the `EXIF Metadata Synchronizer` window. By default it assigns it to "Shot", but I'm not sure "Shot" understands the date-time nature of the field, to drill down and group by date for example.

Is that what you meant?

**Comment by abourget** [comment]
I ended up doing: 
`exiftool "-FileCreateDate<CreateDate" "-FileModifyDate<CreateDate" *.mp4` to tweak filesystem times, and _then_ import into resolve. That works for now. I'd prefer being able to use your method, but we'll see :)

**Comment by deric** [comment]
AFAIK it's not possible to add extra "Date" field into DaVinci Resolve. "Shot" it's the closest attribute that can act like a "Date" attribute.

There are 3 date attributes:

* Date Modified
* Date Created
* Date Added

If I remember this correctly these attributes are read-only (fetched from filesystem properties). When you're sorting clips in Media Pool you can select e.g. "Shot" attribute.

![Screenshot_20211112_154055](https://user-images.githubusercontent.com/138573/141484786-c5483e1c-1555-4be7-9a1b-68a5afa2b19f.png)

**Comment by abourget** [comment]
ok, thanks!
